config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "shoppings#index"
  
  resources :shoppings do 
    resources :items
  end

  post 'shoppings/archive'
  post 'shoppings/search'
  post 'shoppings/search_by_dates'
  post 'items/calculateprice'
  post 'items/paid_item'
  post 'items/set_taken'
  delete 'items/remove'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :shopping

  validates :name, presence: true

  before_save :set_total

  def set_total
    self.total_price = self.unit_price * self.quantity
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	before_action :authenticate_user!
	load_and_authorize_resource except: [:calculateprice, :paid_item, :set_taken]

	rescue_from CanCan::AccessDenied do |exception|
    	redirect_to root_url, :alert => exception.message
  	end

  	def new
  		@shopping = Shopping.find(params[:shopping_id])
	    @item = @shopping.items.new
	    logger.debug @item.shopping_id
	    authorize! :create, @item
  	end

	def create
		@shopping = Shopping.find(params[:shopping_id])
		@item = @shopping.items.create(item_params)
		logger.debug @item.shopping_id
		#@item.set_total(@item.unit_price * @item.quantity)
		#@item.total_price = @item.quantity * @item.unit_price
		respond_to do |format|
			if @item.update(item_params)
				@shopping.total_price = @shopping.total
				@shopping.save
				format.html { redirect_to edit_shopping_path(@shopping), notice: 'Articolo creato con successo.' }
	        	format.json { render action: 'edit', controller: 'shoppings', status: :created, location: edit_shopping_path(@shopping) }
	        	# added:
	       		format.json { render action: 'edit', controller: 'shoppings', status: :created, location: edit_shopping_path(@shopping) }
	      	else
	        	format.html { render action: 'new' }
	        	format.json { render json: @item.errors, status: :unprocessable_entity }
	        	# added:
	        	format.js   { render json: @item.errors, status: :unprocessable_entity }
	      	end
      	end
		#redirect_to edit_shopping_path(@shopping)
	end

	def edit
		@item = Item.find(params[:id])
		authorize! :update, @item
		@shopping = Shopping.find(@item.shopping_id)
		respond_to do |format|
			format.js
		end
	end

	def update
	    @item = Item.find(params[:id])
	    @shopping = Shopping.find(params[:shopping_id])
	    #@item.set_total(item_params[:unit_price], item_params[:quantity])
	    if @item.update(item_params)
	    	@shopping.total_price = @shopping.total
	    	@shopping.save
	      	redirect_to edit_shopping_path(@shopping)
	    else
	      render :edit, status: :unprocessable_entity
	    end
	end

	def destroy
    	@item = Item.find(params[:id])
    	authorize! :destroy, @item
    	@shopping = Shopping.find(@item.shopping_id)
    	@item.destroy

    	redirect_to edit_shopping_path(@shopping), status: :see_other
  	end

	def remove
		@item = Item.find(params[:my][:id])
		authorize! :destroy, @item
		@item.destroy
		@shopping =Shopping.find(@item.shopping_id)
		@shopping.total_price = @shopping.total
		respond_to do |format|
			format.html
			format.js
		end
	end

	def calculateprice
		@item = Item.find(params[:my][:id])
		#authorize! :update, @item
		@k = params[:my][:k]
		@op = params[:my][:op]
		if @op == "sum"
			@item.update_attribute :quantity, @item.quantity + @k.to_i
		else
			if @item.quantity > 1
				@item.update_attribute :quantity, @item.quantity - @k.to_i
			end
		end
		@item.update_attribute :total_price, @item.quantity * @item.unit_price
		@shopping =Shopping.find(@item.shopping_id)
		@shopping.total_price = @shopping.total
		respond_to do |format|
			format.js 
		end
	end

	def paid_item
		@item = Item.find(params[:id])
		#authorize! :update, @item
		if @item.payed?
			@item.update_attribute :payed, false
		else
			@item.update_attribute :payed, true
		end
		@shopping =Shopping.find(@item.shopping_id)
		@paid_items = @shopping.items.where(:payed => true)
		@result_total_price = @paid_items.sum(:total_price)
		respond_to do |format|
			format.js 
		end
	end

	def set_taken
		@item_id = params[:id]
		@taken = params[:taken]
		@item = Item.find(@item_id)
		@item.taken = @taken
		if @item.save
			respond_to do |format|
				format.js 
			end
		else
			format.json { render action: 'edit', controller: 'shoppings', status: :unprocessable_entity }
		end
	end

	private
	def item_params
		params.require(:item).permit(:name, :quantity, :unit_price, :total_price, :payed, :taken)
	end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%# Conditionally set remote: true. Also, passing model name as data attribute %>
<% modal ||= false %>
<% remote = modal ? true : false %>

<%= form_with model: [ @shopping, @item ], remote: remote do |form| %>
  <% if @item.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

        <ul>
        <% @item.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <%= form.hidden_field :shopping_id, value: @shopping.id %>
  <div class="form-group">
    <%= form.label :name %><br>
    <%= form.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :quantity %><br>
    <div class="quantity">
      <span class="quantity-add quantity-button btn btn-success"></span>
      <%= form.number_field :quantity, value: (form.object.quantity || 1), class: 'form-control' %>
      <span class="quantity-remove quantity-button btn btn-warning"></span>
    </div>
  </div>
  <div class="form-group">
    <%= form.label :unit_price %><br>
    <%= form.number_field :unit_price, value: (form.object.unit_price || 0), step: :any, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :total_price %><br>
    <span id="total_price"></span>
  </div>

  <div class="form-group">
    <%= form.submit class: 'btn btn-primary' %>
    <%= link_to "Indietro", edit_shopping_path(@shopping), class: 'btn btn-danger' %>
  </div>
<% end %>
<script>
  $('.quantity-button').off('click').on('click', function () {
  
    if ($(this).hasClass('quantity-add')) {
      var addValue = parseInt($(this).parent().find('input').val()) + 1;
      $(this).parent().find('input').val(addValue)
    }

    if ($(this).hasClass('quantity-remove')) {
      var removeValue = parseInt($(this).parent().find('input').val()) - 1;
      if( removeValue == 0 ) {
        removeValue = 1;
      }
      $(this).parent().find('input').val(removeValue)
    }

  });
</script>

app/views/items/_item.html.erb
<% unless item.id == nil || item.id == 0 %>
<tr id="tr_item_<%= item.id %>" <% if item.taken? %> class="selectedItem"<% end %>>
  <td><input type="checkbox" name="itemChk" class="itemChk" id="itemChk_<%= item.id %>" <% if item.taken? %> checked<% end %>></td>
  <td id="item_name-<%= item.id %>">
    <% if (can? :update, item) && (!item.payed?) %>
      <%= link_to edit_shopping_item_path(item.shopping_id, item), remote: true do %>
        <%= item.name %>
    <% end %>
    <% else %>
        <%= item.name %>
    <% end %>
  </td>
  <td id="item-<%= item.id %>"><%= item.quantity %></td>
  <td><%= item.unit_price %> €</td>
  <td id="total_price-<%= item.id %>"><%= item.total_price.round(2) %> €</td>
  <td id="item_paid-<%= item.id %>">
    <%#<%= link_to "Da Pagare", { controller: 'items', action: :paid_item, id: item.id }, { class: "btn btn-primary btn-xs", method: :post, remote: true} %>
    <% if item.payed? %>
      <%= link_to 'Pagato', {controller: 'items', action: 'paid_item', id: item.id}, 
              method: :post, :remote => true,
              class: "btn btn-success btn-xs" %>
    <% else %>
      <%= link_to 'Da Pagare', {controller: 'items', action: 'paid_item', id: item.id}, 
              method: :post, :remote => true,
              class: "btn btn-primary btn-xs" %>
    <%#<%= link_to controller: 'items', action: 'calculateprice', id: item.id, method: :post, :remote => true,
              class: "btn btn-warning btn-xs" do %>
    <% end %>
  </td>
  <td>
    <% if can? :update, item %>
      <%= link_to '-1', {controller: 'items', action: 'calculateprice', 
              my: {id: item.id, k: '1', op: 'min'}}, 
              method: :post, :remote => true,
              class: "btn btn-warning btn-xs" %>
            
      <%= link_to '+1', {controller: 'items', action: 'calculateprice', 
              my: {id: item.id, k: '1', op: 'sum'}}, 
              method: :post, :remote => true,
              class: "btn btn-info btn-xs" %>
        <%#</div>#%>
    <% end %>
  </td>
  <td>
    <div class="button-container">
      <% if can? :update, item %>
        <%= link_to edit_shopping_item_path(item.shopping_id, item), remote: true, class: 'btn btn-success btn-xs' do %>
          <i class="fa fa-pencil-square-o"></i>
        <% end %>
      <% end %>
      <% if can? :destroy, item %>
        <%= button_to shopping_item_path(item.shopping_id, item.id), class: 'btn btn-danger btn-xs', method: :delete do %>
          <i class="fa fa-trash"></i>
        <% end %>
      <% end %>
    </div>
  </td>
</tr>
<% end %>

app/views/items/calculateprice.js.erb
$("#item-<%= @item.id %>").html("<%= @item.quantity %>")
$("#total_price-<%= @item.id %>").html("<%= @item.total_price.round(2) %> €")
$("#shoppingTotal-<%= @shopping.id %>").html("<%= @shopping.total_price %>")

app/views/items/create.js.erb
$('#items-<%= @shopping.id %> > tbody:last-child').append('<tr id="tr_item_<%= item.id %>">' + 
  '<td><%= item.name %></td>' +
  '<td id="item-<%= item.id %>"><%= item.quantity %></td>' +
  '<td><%= item.unit_price %> €</td>' + 
  '<td id="total_price-<%= item.id %>"><%= item.total_price.round(2) %> €</td>' +
  '<td><%= link_to "-1", {controller: "items", action: "calculateprice", my: {id: item.id, k: "1", op: "min"}}, :method => :post, :remote => true, class: "btn btn-warning btn-xs" %> ' +
  '<td><%= link_to "+1", {controller: "items", action: "calculateprice", my: {id: item.id, k: "1", op: "sum"}}, :method => :post, :remote => true, class: "btn btn-info btn-xs" %>' +
  '</td>' + 
  '<td>' +
    '<%= link_to "Modifica", edit_shopping_item_path(item), :remote => true, class: "btn btn-success btn-xs" %> <%= link_to "Elimina", {controller: "items", action: "remove", my: {id: item.id}}, :method => :delete, :remote => true, class: "btn btn-danger btn-xs" %>' +
  '</td>' +
'</tr>');

app/views/items/edit.html.erb
<h2>Modifica Articolo</h2>
<div id="divform">
<%= render 'items/form' %>
</div>

app/views/items/edit.js.erb
$('#myModalLabel').html("Modifica Articolo")
$('.modal-body').html("<%= escape_javascript( render partial: 'form', locals: {group: @item} ) %>")

$('#new_item_modal').modal()

app/views/items/new.html.erb
<h2>Aggiungi articoli</h2>
<div id="divform">
<%= render 'items/form' %>
</div>

app/views/items/paid_item.js.erb
<% if @item.payed? %> 
	$("#item_name-<%= @item.id %>").html('<%= @item.name %>');
	$("#item_paid-<%= @item.id %>").html('<%= link_to "Pagato", {controller: "items", action: "paid_item", id: @item.id}, { class: "btn btn-success btn-xs", method: :post, remote: true} %>');
<% else %>
	$("#item_name-<%= @item.id %>").html('<%= link_to edit_shopping_item_path(@item.shopping_id, @item), remote: true do %><%= @item.name %><% end %>');
	$("#item_paid-<%= @item.id %>").html('<%= link_to "Da Pagare", {controller: "items", action: "paid_item", id: @item.id}, { class: "btn btn-primary btn-xs", method: :post, remote: true} %>');
<% end %>

$("#shoppingPaid-<%= @shopping.id %>").html("<%= @result_total_price %>");

app/views/items/remove.js.erb
let delete<%= @item.id %> = document.querySelector("#tr_item_" + <%= @item.id %>);
delete<%= @item.id %>.remove();

$("#shoppingTotal-<%= @shopping.id %>").html("<%= @shopping.total_price %>");

app/views/items/set_taken.js.erb
$('#tr_item_<%= @item_id %>').toggleClass("selectedItem");