config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "shoppings#index"
  
  resources :shoppings do 
    resources :items
  end

  post 'shoppings/archive'
  post 'shoppings/search'
  post 'shoppings/search_by_dates'
  post 'items/calculateprice'
  post 'items/paid_item'
  post 'items/set_taken'
  delete 'items/remove'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/shopping.rb
class Shopping < ApplicationRecord
	belongs_to :user
	has_many :items, dependent: :destroy

	VALID_STATUSES = ['nuovo', 'pagato']

  	validates :status, inclusion: { in: VALID_STATUSES }

	def archived?
		status == 'pagato'
	end

	def total
		self.items.sum(:total_price)
  	end

  	def self.by_dates(date_start, date_end)
  		Shopping.where(:date_shopping => @date_start..@date_end).order(date_shopping: :asc)
  	end
end

app/controllers/shoppings_controller.rb
class ShoppingsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource except: [:search, :search_by_dates]

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end

  def index
    @shoppings = Shopping.where(:user_id => current_user.id).order(date_shopping: :asc)
    @result_total_price = @shoppings.sum(:total_price)
  end

  def search
    @shoppings = nil
    @errMsg = ''
    logger.debug "Dentro Search"
    @period = params[:period]
    if @period.present?
      logger.debug "Period: #{@period}"
      if @period == '1'
        logger.debug "Tutte"
        @shoppings = Shopping.where(:user_id => current_user.id).order(date_shopping: :asc)
      elsif @period == '2'
        logger.debug "Ultimi 7 giorni"
        @date_end = Date.today
        @date_start = @date_end - 7
        @shoppings = Shopping.where(:user_id => current_user.id).where(:date_shopping => @date_start..@date_end).order(date_shopping: :asc)
      elsif @period == '3'
        logger.debug "Ultimi 30 giorni"
        @date_end = Date.today
        @date_start = @date_end - 30
        @shoppings = Shopping.where(:user_id => current_user.id).where(:date_shopping => @date_start..@date_end).order(date_shopping: :asc)
      end
    else
      logger.debug "No parametri"
      @shoppings = Shopping.where(:user_id => current_user.id).order(date_shopping: :asc)
    end
    @result_total_price = @shoppings.sum(:total_price)
    respond_to do |format|
      format.html
      format.js
    end
  end

  def search_by_dates
    @shoppings = nil
    @errMsg = ''
    @result_total_price = 0
    @date_start = params[:date_start]
    @date_end = params[:date_end]
    logger.debug "Date Start: #{@date_start}"
    logger.debug "Date End: #{@date_end}"
    if @date_start > @date_end
      @errMsg = 'La data iniziale non può essere maggiore della data finale'
    elsif @date_start == '' || @date_end == ''
      @errMsg = 'Specificare date inziale e finale della ricerca'
    else
      @shoppings = Shopping.where(:user_id => current_user.id).where(:date_shopping => @date_start..@date_end).order(date_shopping: :asc)
      @result_total_price = @shoppings.sum(:total_price)
      #authorize! :read, @shoppings
      respond_to do |format|
        format.html
        format.js
      end
    end
  end

  def show
    @shopping = Shopping.find(params[:id])
    authorize! :read, @shopping
  end

  def new
    @shopping = Shopping.new
    authorize! :create, @shopping
    @shopping.date_shopping = Time.now
    @shopping.status='nuovo'
    @shopping.user_id = current_user.id
    if @shopping.save
      redirect_to edit_shopping_path(@shopping)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def create 
    @shopping = Shopping.new
    @shopping.date_shopping = Time.now
    @shopping.status='nuovo'
    if @shopping.save
      redirect_to @shopping
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @shopping = Shopping.find(params[:id])
    authorize! :update, @shopping
    @item = @shopping.items.new
    @paid_items = @shopping.items.where(:payed => true)
    @result_total_price = @paid_items.sum(:total_price)
  end

  def update
    @shopping = Shopping.find(params[:id])
    #@shopping.user_id = current_user.id
    if @shopping.update(shopping_params)
      if @shopping.status = 'pagato'
        @shopping.items.update_all(payed: true)
      end
      redirect_to @shopping
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @shopping = Shopping.find(params[:id])
    authorize! :destroy, @shopping
    @shopping.destroy

    redirect_to root_path, status: :see_other
  end

  def archive
    @shopping = Shopping.find(params[:my][:id])
    authorize! :update, @shopping
    @shopping.status = "pagato"
    if @shopping.save
      redirect_to @shopping
    else
      render :new, status: :unprocessable_entity
    end
  end

  private 
  def shopping_params
    params.require(:shopping).permit(:date_shopping, :total_price, :status, :user_id)
  end
end

app/helpers/shoppings_helper.rb
module ShoppingsHelper
end

app/views/shoppings/_form.html.erb
<%= form_with model: @shopping do |form| %>
	<%= form.submit %>
<% end %>

app/views/shoppings/_shoppinglists.html.erb
<% if @errMsg != '' %>
	<h4 class="text-muted" style="color:red;"><%= @errMsg %></h4>
<% elsif @date_start.present? && @date_end.present? %>
	<h4 class="text-muted">Spese dal <%= @date_start %> al <%= @date_end %></h4>
<% end %>

<div>
	<div class="row">
		<div class="col-lg-12">
			<div class="main-box-clearfix">
				<div class="table-responsive">
					<table class="table user-list" id="list-shopping">
						<thead>
							<tr>
								<th><span>Totale</span></th>
								<th><span>Data</span></th>
								<th><span>Stato</span></th>
								<th></th>
							</tr>
						</thead>
						<tbody>
							<% unless @shoppings == nil %>
								<% @shoppings.each do |shopping| %>
									<tr>
										<td>
											<i class="fa fa-money"></i>
											<span class="user-link"><%= shopping.total.round(2) %> €</span>
										</td>
										<td><%= shopping.date_shopping.strftime("%d/%m/%Y") %></td>
										<td>
											<% if !shopping.archived? %> 
						 						<span class="badge badge-success"> 
						 							<i class="fa fa-shopping-cart"></i>
						 							<%= shopping.status.capitalize %>
						 					<% else %>
												<span class="badge badge-warning"><i class="fa fa-credit-card">	</i>
												<%= shopping.status.capitalize %>
						 						</span>
											<% end %>
										</td>
										<td>
											<% if can? :read, shopping %>
												<%= link_to shopping, class:'btn btn-xs btn-info' do %>
													<i class="fa fa-search-plus"></i>
												<% end %>
											<% end %>
											<% if can? :update, shopping %>
												<% unless shopping.archived? %>
													<%= link_to edit_shopping_path(shopping), class: 'btn btn-xs btn-success' do %>
														<i class="fa fa-pencil-square-o"></i>
													<% end %> 
												<% end %>
											<% end %>
											<% if can? :destroy, shopping %>
												<% unless shopping.archived? %>
												    <%= link_to shopping, class:'btn btn-xs btn-danger', method: :delete do %>
														<i class="fa fa-trash"></i>
													<% end %>
												<% end %>
											<% end %>
										</td>
									</tr>
								<% end %>
							<% end %>
						</tbody>
						<tfoot>
							<tr>
								<th>Totale: <%= @result_total_price.round(2) %> €</th>
								<td></td>
								<td></td>
								<td></td>
						</tfoot>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>

<!--
<table class="table table-striped">
	<thead>
		<tr>
			<th>Data</th>
			<th>Totale</th>
			<th>Stato</th>
			<th></th>
		</tr>
	</thead>
	<tbody>

			<%# <% @shoppings.each do |shopping| %>
			<tr>
				<td><%# <%= shopping.date_shopping.strftime("%d/%m/%Y") %></td>
				<td><%# <%= shopping.total.round(2) %> €</td>
				<td>
					<%# <% if !shopping.archived? %> 
					 <span class="badge badge-success"> 
					 	<i class="fa fa-shopping-cart"></i>
					 	<%# <%= shopping.status.capitalize %>
					 <%# <% else %>
					<span class="badge badge-warning"><i class="fa fa-credit-card"></i>
						<%# <%= shopping.status.capitalize %>
					 </span>
					<%# <% end %>
				</td>
				<td>
					<%# <% if can? :read, shopping %>
						<%# <%= link_to shopping, class:'btn btn-xs btn-info' do %>
							<i class="fa fa-file-text-o"></i> Vedi
						<%# <% end %>
					<%# <% end %>
					<%# <% if can? :update, shopping %>
					<%# 	<% unless shopping.archived? %>
							<%# <%= link_to edit_shopping_path(shopping), class: 'btn btn-xs btn-success' do %>
								<i class="fa fa-pencil-square-o"></i> Modifica
						<%# 	<% end %> 
						<%# <% end %>
					<%# <% end %>
				</td>
			</tr>
			<%# <% end %>
	</tbody>
	<tfoot>
		<tr>
			<th>Totale</th>
			<td><%# <%= @result_total_price.round(2) %> €</td>
			<td></td>
	</tfoot>
</table>-->

app/views/shoppings/edit.html.erb
<h1>Spesa</h1>
<p><i class="fa fa-calendar"></i> <b>Data:</b> <%= @shopping.date_shopping.strftime("%d/%m/%Y") %></p>
<p><i class="fa fa-money"></i> <b>Totale:</b> <span id="shoppingTotal-<%= @shopping.id %>"><%= @shopping.total.round(2) %> </span>€</p>
<p><i class="fa fa-credit-card"></i> <b>Totale Pagato:</b> <span id="shoppingPaid-<%= @shopping.id %>"><%= @result_total_price.round(2) %> </span>€</p>
<div class="button-container">
  <% if can? :update, @shopping %>
    <% if @shopping.total > 0 %>
      <%= form_with model: @shopping, url: shopping_path(@shopping.id), method: :put do |form| %>
        <%= form.hidden_field :status, value: 'pagato' %>
        <%= button_tag( :class => "btn btn-warning") do %>
          <i class="fa fa-credit-card"></i> Pagata
        <% end %>
      <% end %>
    <% end %>
   <% end %>
  <% if can? :destroy, @shopping %>
    <%= link_to @shopping, class:'btn btn-danger', method: :delete do %>
      <i class="fa fa-trash"></i> Cancella
    <% end %>
    <%#<%= button_to "Cancella", @shopping, class: 'btn btn-danger', method: :delete %>
  <% end %>
</div>
<br><br>
<h2>Articoli</h2>
<%= link_to '#new_item_modal', 'data-toggle' => 'modal', class: "btn btn-info" do %>
  <i class="fa fa-cart-plus"></i> Nuovo Articolo
<% end %>

<table class="table table-striped" id="items-<%= @shopping.id %>">
  <thead>
    <tr>
      <th></th><th>Articolo</th><th>Quantità</th><th>Prezzo Unitario</th><th>Prezzo Tot.</th><th></th><th></th><th></th>
    </tr>
  </thead>
  <tbody>

    <%= render @shopping.items %>

  </tbody>
</table>

<%# Bootstrap modal markup. @see: http://getbootstrap.com/javascript/#modals %>
<div class="modal fade" id="new_item_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Crea nuovo articolo</h4>
      </div>
      <div class="modal-body">
        <%# Render the new item form (passing modal => true to enable remote => true) %>
        <%= render 'items/form', modal: true %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<script>
  $('.itemChk').click(function() {
    //$(this).closest('tr').toggleClass("selectedItem");
    var id = $(this).attr('id').split('_')[1];

    $.ajax({
      url: '/items/set_taken',
      type: 'POST',
      data: {"id": id, "taken": this.checked}
    });
  });

  $('[data-dismiss=modal]').on('click', function (e) {
    var $t = $(this),
        target = $t[0].href || $t.data("target") || $t.parents('.modal') || [];

  $(target)
    .find("[type=text]")
       .val('')
       .end()
    .find("[type=number]")
       .val('')
       .end();

  $(target)
    .find("[type=submit]")
       .val('Create Item');

  $('#item_quantity', target).val('1');
  $('#item_unit_price', target).val('0.0');
  $('#myModalLabel', target).text('Crea nuovo articolo');

  $(target).find('form').attr('action', '/shoppings/<%= @shopping.id %>/items')
});

$(document).ready( function () {
    $('#items-<%= @shopping.id %>').DataTable({
      paging: false, 
      columnDefs: [
      { orderable: false, targets: [0,6,7] }
      ],
      order: [[1, 'desc']]
    });
});
</script>

app/views/shoppings/edit.js.erb
$('#items-<%= @shopping.id %> > tbody:last-child').append("<%= j render partial: 'items/item', locals: {item: @item } %>");
$('#new_item_modal').modal_success();

app/views/shoppings/index.html.erb
<% if user_signed_in? %> 

  <h1>Shoppings List</h1>
	<%= link_to new_shopping_path, method: :get, class: "btn btn-info margin-down" do %>
		<i class="fa fa-cart-plus fa-2"></i> Nuova Spesa
	<% end %>
	<%= form_with url:  shoppings_search_path, :id => 'my-form', local: false, data: { turbolinks: false }  do |form| %>
		<div class="form-group">
			<div class="row">
				<div class="col-md-3 col-sm-3 col-xs-6">
			 		<%= form.radio_button :period, 1 %> 
					<%= form.label :period, 'Tutte', class:'label_index' %>
				</div>
				<div class="col-md-3 col-sm-3 col-xs-6">
					<%= form.radio_button :period, 2 %> 
					<%= form.label :period, 'Ultimi 7 giorni', class:'label_index' %>
				</div>
				<div class="col-md-3 col-sm-3 col-xs-6">
					<%= form.radio_button :period, 3 %> 
					<%= form.label :period, 'Ultimi 30 giorni', class:'label_index' %>
				</div>
				<div class="col-md-3 col-sm-3 col-xs-6">
					<%= form.radio_button :period, 4 %> 
					<%= form.label :period, 'Cerca per date', class:'label_index' %>
				</div>
			<%#<%= form.submit '', id: 'submitMyForm' %>
			</div>
		</div>
	<% end %>
	<div id = 'form_search_dates' style='display: none;'>
			<label>Ricerca per date</label>
			<%= form_with url: shoppings_search_by_dates_path, local: false do |form| %>
			<%#<%= form_with url: shoppings_path, method: :get do |form| %>
				<div class="form-group">
					<div class="row">
						<div class="col-md-3 col-sm-3 col-xs-6">
							<%= form.label :date_start %>
							<%= form.date_field :date_start, attribute: 'date' %>
						</div>
						<div class="col-md-3 col-sm-3 col-xs-6">
							<%= form.label :date_end %>
							<%= form.date_field :date_end, attribute: 'date' %>
						</div>
						<div class="col-md-3 col-sm-3 col-xs-6">
							<%= button_tag( :class => "btn btn-primary") do %>
      					<i class="fa fa-calendar"></i> Cerca
    					<% end %>
							<%# <%= form.submit "Cerca", class: 'btn btn-primary' %>
						</div>
						<div class="col-md-3 col-sm-3 col-xs-6">
						</div>
					</div>
				</div>
			<% end %>
	</div>
	<div id="shoppingTable">
		<%= render 'shoppinglists' %>
	</div>
<% else %>
  <%= button_to "Sign in", new_user_session_path %> 
<% end %>

<script>
  $(document).ready( function () {
  	$.fn.dataTable.moment( 'DD/MM/YYYY' );

  	$('#list-shopping').DataTable({
  		searching: false, 
  		columnDefs: [
   		{ orderable: false, targets: [3] }
			],
			order: [[1, 'desc']]
  	});
	} );
</script>

app/views/shoppings/new.html.erb
<h1>Nuova Spesa</h1>
<p>Totale: <span id="shoppingTotal-<%= @shopping.id %>"><%= @shopping.total %> </span>€</p>

<h2>Articoli</h2>
<table class="table table-striped" id="items-<%= @shopping.id %>">
  <thead>
    <tr>
      <th>Articolo</th><th>Quantità</th><th>Prezzo Unitario</th><th>Prezzo Tot.</th><th></th><th></th>
    </tr>
  </thead>
  <tbody>

    <%= render @shopping.items %>

  </tbody>
</table>

<h2>Aggiungi articoli</h2>
<%= render 'items/form' %>

<ul>
  <% if can? :update, @shopping %>
    <li><%= link_to "Edit", edit_shopping_path(@shopping), class: 'btn btn-success' %></li>
  <% end %>
  <% if can? :destroy, @shopping %>
    <li><%= link_to "Destroy", shopping_path(@shopping), class: 'btn btn-danger', data: { 
    	turbo_method: :delete,
    	turbo_confirm: "Sei sicuro?"
    } %>
    </li>
  <% end %>
</ul>

<%= render "form", shopping: @shopping %>

app/views/shoppings/search.js.erb
$('#shoppingTable').html("<%= j render partial: 'shoppinglists' %>");
$(document).ready( function () {
	$('#list-shopping').DataTable({searching: false, columnDefs: [
   		{ orderable: false, targets: [3] }
		],order: [[1, 'desc']]});
} );

app/views/shoppings/search_by_dates.js.erb
$('#shoppingTable').html("<%= j render partial: 'shoppinglists' %>");
$(document).ready( function () {
	$('#list-shopping').DataTable({searching: false, columnDefs: [
   		{ orderable: false, targets: [3] }
		],order: [[1, 'desc']]});
} );

app/views/shoppings/show.html.erb
<div class="holder align-items-center justify-content-center">
  <div class="container">
    <header class="text-center mb-5">
      <h1 class="display-4">Dettaglio Spesa</h1>
      <p class="fst-italic text-muted subheading"><i class="fa fa-money"></i> Totale: <%= @shopping.total.round(2) %> €</p>
    </header>

    <div class="row rowCenter">
      <div class="col-lg-5 mx-auto">
        <div class="card rounded border-0 shadow-sm position-relative">
          <div class="card-body p-5">
            <div class="d-flex align-items-center mb-4 pb-4 border-bottom">
              <i class="fa fa-calendar fa-3x"></i>
              <div class="ms-3">
                <h4 class="text-uppercase fw-weight-bold mb-0" style="padding-top: 10px; padding-left: 10px;">
                  <%= @shopping.date_shopping.strftime("%A") %>
                </h4>
                <p class="text-gray fst-italic mb-0" style="padding-left: 10px;"><%= @shopping.date_shopping.strftime("%d") %>
                    <%= @shopping.date_shopping.strftime("%B") %> <%= @shopping.date_shopping.strftime("%Y") %>
                </p>
              </div>
            </div>
            <table class="table" id="items-<%= @shopping.id %>">
              <thead>
                <tr>
                  <th>Articolo</th><th>Prezzo Unitario</th><th>Quantità</th><th>Prezzo Tot.</th>
                </tr>
              </thead>
              <tbody>
                <% @shopping.items.each do |item| %>
                  <tr>
                    <td><span class="fst-italic pl-1"><%= item.name %></span></td>
                    <td><%= item.unit_price %> €</td>
                    <td><%= item.quantity %></td>
                    <td id="total_price-<%= item.id %>"><%= item.total_price.round(2) %> €</td>
                  </tr>
                <% end %>
              </tbody>
              <tfoot>
                <tr>
                  <td></td>
                  <td></td>
                  <th>Totale</th>
                  <th><%= @shopping.total.round(2) %> €</th>
                </tr>
              </tfoot>
            </table>            
          </div>
        </div>
        <% if can? :update, @shopping %>
        <% unless @shopping.archived? %>
          <%= link_to edit_shopping_path(@shopping), class: 'btn btn-success' do %>
            <i class="fa fa-pencil-square-o"></i> Edit
          <% end %>
        <% end %>
      <% end %>
      </div>

  </div>

</div>